academy_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns 
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns =[
    path('i18n/', include('django.conf.urls.i18n')),
    path('checkout/', include('checkout.urls')),
]

urlpatterns += i18n_patterns(
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('courses.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path 
from blog import views 


urlpatterns = [
    path('posts/', views.PostListView.as_view(), name='Posts_list'), 
    path('myposts/', views.UserPostListView.as_view(), name='MyPosts_list'), 
    path('post/detail/<int:pk>/', views.PostDetailView.as_view(), name='Post_detail'), 
    path('post/create/', views.PostCreateView.as_view(), name='Post_create'), 
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='Post_update'), 
    path('post/delete/<int:pk>/', views.PostDeleteView.as_view(), name='Post_delete'), 
    path('post/create/comment/', views.CommentCreateView.as_view(), name='Comment_create'), 

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models.signals import post_save



class Post(models.Model): 
    title = models.CharField(max_length=155)
    image = models.ImageField(upload_to='posts/', null=True)
    content = RichTextUploadingField() 
    
    author = models.ForeignKey(User, on_delete=models.PROTECT) 
    slug = models.SlugField() 

    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    
    def save(self, *args, **kwargs):
        if not self.slug: 
            self.slug = slugify(self.title) 
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-created_at', )

        
    def __str__(self) -> str:
        return self.title 
    


class Comment(models.Model): 
    body = models.TextField() 

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_comment') 
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 

    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 


    def __str__(self): 
        return self.body     
    

courses/models.py
from django.db import models
from django.contrib.auth.models import User 
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import gettext_lazy as _ 
from django.db.models.signals import post_save 


class Course(models.Model):
    name = models.CharField(_('Name'),max_length=155)
    name_en = models.CharField(_('Name_en'),max_length=155, blank=True, null=True)

    image = models.ImageField(_('Image'),upload_to='courses/')
    price = models.FloatField(_('Price')) 
    short_description = models.TextField(_('Short_description')) 
    short_description_en = models.TextField(_('Short_description_en'),blank=True, null=True) 
    description = models.TextField(_('Description'))
    description_en = models.TextField(_('Description_en'), blank=True, null=True)
    info = models.TextField(_('Info'))
    info_en = models.TextField(_('Info_en'),blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self) -> str:
        return self.name 
    class Meta:
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')


class Section(models.Model): 
    name = models.CharField(_('Name') ,max_length=155) 
    name_en = models.CharField(_('Name_en') ,max_length=155, blank=True, null=True) 

    # relational fields 
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 
    class Meta:
        verbose_name = _('Section')
        verbose_name_plural = _('Sections')


    
    def __str__(self): 
        return self.name 
    

class Lesson(models.Model): 
    name = models.CharField(_('Name'),max_length=155) 
    name_en = models.CharField(_('Name_en'),max_length=155, blank=True, null=True) 
    description = models.TextField(_('Description'),max_length=500, null=True, blank=True) 
    description_en = models.TextField(_('Description_en'),max_length=500, null=True, blank=True) 
    video = models.FileField(_('Video'),upload_to='lessons/') 
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    # relational fields 
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')

    def __str__(self): 
        return self.name 
    

class Comment(models.Model): 
    body = RichTextUploadingField(_('Body')) 
    # relational fields
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE) 
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    to_user = models.CharField(max_length=100, null=True)


    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 
    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self): 
        return self.lesson.name + '>' + self.user.username 
    


class StudentCourses(models.Model):     
    user = models.ForeignKey(User, on_delete=models.CASCADE)  
    course = models.ForeignKey(Course, on_delete=models.CASCADE) 
    amount_paid = models.FloatField(blank=True, null=True) 
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 


class Notification(models.Model): 
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True) 
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    to_user = models.CharField(max_length=100, null=True) 
    is_seen = models.BooleanField(default=False) 

    created_at = models.DateTimeField(auto_now_add=True, null=True) 
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    class Meta: 
        ordering = ['-created_at', 'is_seen']
    def __str__(self): 
        return self.from_user.username



def create_notication(sender, instance, created, **kwargs): 
    if created: 
        Notification.objects.create(
            lesson= instance.lesson,
            comment = instance, 
            from_user = instance.user,
            to_user = instance.to_user
        )
post_save.connect(create_notication, sender=Comment)

blog/forms.py
from django import forms
from blog.models import Post, Comment 
from ckeditor.widgets import CKEditorWidget
from django.utils.translation import gettext as _ 



attrs= {'class': 'form-control'}

class PostCreateForm(forms.ModelForm): 
    class Meta: 
        model = Post
        fields = ['title', 'content', 'image']
        labels = {
            'title': _('Title'),
            'content': _('Content'),
            'image': _('Image'),
        }
        widgets={
            'title':forms.TextInput(attrs=attrs), 
            'content':forms.CharField(widget=CKEditorWidget(attrs=attrs)),
        }




class PostUpdateForm(forms.ModelForm): 
    class Meta: 
        model = Post
        fields = ['title', 'content', 'image']
        labels = {
            'title': _('Title'),
            'content': _('Content'),
            'image': _('Image'),
        }
        widgets={
            'title':forms.TextInput(attrs=attrs), 
            'content':forms.CharField(widget=CKEditorWidget(attrs=attrs)) 
        }

blog/views.py
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Comment, Post 
from blog.forms import PostCreateForm, PostUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin 




class PostListView(ListView): 
    model = Post 
    template_name = 'posts/posts_list.html'
    paginate_by = 6

    def get_queryset(self):
        query = super().get_queryset()
        q = self.request.GET.get('q', None)
        where = {}
        if q:
            where['title__icontains'] = q
        return query.filter(**where)
    
class UserPostListView(ListView): 
    model = Post 
    template_name = 'posts/posts_list.html'
    paginate_by = 3
    def get_queryset(self):
        query = super().get_queryset()
        q = self.request.GET.get('q', None)
        where = {'author': self.request.user}
        if q:
            where['title__icontains'] = q
        return query.filter(**where)
    


class PostDetailView(DetailView): 
    model = Post 
    template_name = 'posts/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView): 
    model = Post 
    form_class = PostCreateForm
    template_name = 'posts/post_create.html'
    success_url = reverse_lazy('Posts_list')
    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView): 
    model = Post 
    form_class = PostUpdateForm
    template_name = 'posts/post_update.html'

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('Post_detail', kwargs={'pk': self.object.id})


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView): 
    model = Post 
    template_name = 'posts/post_delete.html' 
    success_url = reverse_lazy('Posts_list')

    def test_func(self):
        return self.get_object().author == self.request.user



class CommentCreateView(LoginRequiredMixin, CreateView): 
    model = Comment
    fields = ['body','post']
    http_method_names = ['post']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse('Post_detail', args=[self.object.post.id])

    

blog/templates/parts/comments.html
{% load i18n %}
<div class="container mb-5 mt-5">
    <div class="card-header">
    {% trans "Comments" %} {{post.comment_set.all.count}}
    </div>
    {% for comment in post.comment_set.all %}
    <div class="card">
        <div class="card-header">
        {{comment.user.username}}
        </div>
        <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p>{{ comment.body }}</p>
            <footer class="blockquote-footer">{% trans "Date" %}: {{comment.created_at|date:'D-m-Y'}}</footer>
        </blockquote>
        </div>
    </div>
    {% empty %}
    <div class="card">
        <div class="card-header">
        <h3>No comment yet</h3>
        </div>
    </div>
    {% endfor %}
    <div class="card">
    <form method="post" action="{% url 'Comment_create' %}">
        <div class="form-group">
            {% csrf_token %}
            <input type="hidden" value="{{post.id}}" name="post" />
            <!-- <input type="text" name="body" placeholder="{% trans 'Write a comment' %}"/> -->
            <textarea name='body' placeholder="{% trans "write a comment" %}" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>

            <input type="submit"class="btn btn-primary btn-lg btn-block" value="{% trans "Comment" %}">
        </div>
    </form>

    </div>


</div>

blog/templates/parts/footer.html
{% load i18n%}
<footer class="footer mt-auto py-4 bg-secondary">
    <div class="container text-center">
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
        <select name="language">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="Go">
    </form>
    <script>
      let language_code = '{{LANGUAGE_CODE}}'
      let all_content = document.getElementById('all_content'); 

      if (language_code == 'en'){
        all_content.dir = 'ltr';
        all_content.lang = 'en';
      }else{
        all_content.dir = 'rtl';
        all_content.lang = 'ar';
      }

    </script>
      <span class="text text-light">{% trans '© 2022 All rights reseerved' %}.</span>
    </div>
  </footer>

blog/templates/parts/header.html
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'Posts_list' %}">{% trans "Blog" %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Posts_list' %}">{% trans "Home" %} <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'MyPosts_list' %}">{% trans "My Posts" %}</a>
        </li>
        <li>
          <a class="nav-link mx-1" href="{% url 'notifications' %}" role="button">
          {% trans "Notification" %}
          <span class="badge badge-primary badge-pill text-secondary">({{ un_seen }})</span>
          </a>

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'profile' %}">{% trans "Profile" %}</a>
            <div class="dropdown-divider"></div>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <!-- <a class="dropdown-item" href="{% url 'logout' %}">{% trans "Logout" %}</a> -->
                  <a href="#" class="dropdown-item" onclick="document.getElementById('logout-form').submit()"> 
                    {% translate 'Log out' %}
                  </a>
                </form>
          </div>
        </li>
        {% if user.studentcourses_set.count > 0 %}
        <li class="nav-item">
            <a class="nav-link " href="{% url 'MyCourses' %}">{% trans "My Courses" %}</a>
        </li>
        {% endif %}
      </ul>
      <form action="{% url 'Posts_list' %}" class="form-inline my-2 my-lg-0">
        <input name="q" value="{{request.GET.q}}" class="form-control mr-sm-2" type="search" placeholder="{% trans 'Search' %}" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
      </form>
    </div>
  </nav>