academy_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns 
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns =[
    path('i18n/', include('django.conf.urls.i18n')),
    path('checkout/', include('checkout.urls')),
]

urlpatterns += i18n_patterns(
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('courses.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path 
from blog import views 


urlpatterns = [
    path('posts/', views.PostListView.as_view(), name='Posts_list'), 
    path('myposts/', views.UserPostListView.as_view(), name='MyPosts_list'), 
    path('post/detail/<int:pk>/', views.PostDetailView.as_view(), name='Post_detail'), 
    path('post/create/', views.PostCreateView.as_view(), name='Post_create'), 
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='Post_update'), 
    path('post/delete/<int:pk>/', views.PostDeleteView.as_view(), name='Post_delete'), 
    path('post/create/comment/', views.CommentCreateView.as_view(), name='Comment_create'), 

]

courses/urls.py
from django.urls import path 
from . import views



urlpatterns = [
    path('', views.courses_list, name="Courses_list"), 
    path('notifications/', views.notification_view, name='notifications'),
    path('course/detail/<int:cid>/', views.course_detial, name="Course_detail"), 
    path('mycourse/', views.my_courses, name="MyCourses"), 
    path('course/sections/<int:cid>/', views.sections, name="Course_section"), 
    path('course/section/lessons/<int:sid>/', views.lesson_list, name="Course_section_lessons"), 
    path('course/section/lessons/lesson/<int:lid>/', views.lesson, name="Lesson"), 
    # path('course/section/lesson/comment/', views.CommentCreateView.as_view(), name="Lesson_comment"), 
]

courses/models.py
from django.db import models
from django.contrib.auth.models import User 
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import gettext_lazy as _ 
from django.db.models.signals import post_save 


class Course(models.Model):
    name = models.CharField(_('Name'),max_length=155)
    name_en = models.CharField(_('Name_en'),max_length=155, blank=True, null=True)

    image = models.ImageField(_('Image'),upload_to='courses/')
    price = models.FloatField(_('Price')) 
    short_description = models.TextField(_('Short_description')) 
    short_description_en = models.TextField(_('Short_description_en'),blank=True, null=True) 
    description = models.TextField(_('Description'))
    description_en = models.TextField(_('Description_en'), blank=True, null=True)
    info = models.TextField(_('Info'))
    info_en = models.TextField(_('Info_en'),blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self) -> str:
        return self.name 
    class Meta:
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')


class Section(models.Model): 
    name = models.CharField(_('Name') ,max_length=155) 
    name_en = models.CharField(_('Name_en') ,max_length=155, blank=True, null=True) 

    # relational fields 
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 
    class Meta:
        verbose_name = _('Section')
        verbose_name_plural = _('Sections')


    
    def __str__(self): 
        return self.name 
    

class Lesson(models.Model): 
    name = models.CharField(_('Name'),max_length=155) 
    name_en = models.CharField(_('Name_en'),max_length=155, blank=True, null=True) 
    description = models.TextField(_('Description'),max_length=500, null=True, blank=True) 
    description_en = models.TextField(_('Description_en'),max_length=500, null=True, blank=True) 
    video = models.FileField(_('Video'),upload_to='lessons/') 
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    # relational fields 
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')

    def __str__(self): 
        return self.name 
    

class Comment(models.Model): 
    body = RichTextUploadingField(_('Body')) 
    # relational fields
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE) 
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    to_user = models.CharField(max_length=100, null=True)


    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 
    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self): 
        return self.lesson.name + '>' + self.user.username 
    


class StudentCourses(models.Model):     
    user = models.ForeignKey(User, on_delete=models.CASCADE)  
    course = models.ForeignKey(Course, on_delete=models.CASCADE) 
    amount_paid = models.FloatField(blank=True, null=True) 
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 


class Notification(models.Model): 
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True) 
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    to_user = models.CharField(max_length=100, null=True) 
    is_seen = models.BooleanField(default=False) 

    created_at = models.DateTimeField(auto_now_add=True, null=True) 
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    class Meta: 
        ordering = ['-created_at', 'is_seen']
    def __str__(self): 
        return self.from_user.username



def create_notication(sender, instance, created, **kwargs): 
    if created: 
        Notification.objects.create(
            lesson= instance.lesson,
            comment = instance, 
            from_user = instance.user,
            to_user = instance.to_user
        )
post_save.connect(create_notication, sender=Comment)

courses/forms.py
from django import forms
from courses.models import Comment 
from ckeditor.widgets import CKEditorWidget
from django.utils.translation import gettext as _ 



attrs = {'class':'form-control', 'required':True}


class CommentForm(forms.ModelForm): 
    class Meta: 
        model = Comment
        fields = ['body']
        labels = {
            'body': _('Body') 
        }
        widgets={
            'body': forms.CharField(widget=CKEditorWidget(attrs=attrs))
        }
        

courses/views.py
import re
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from academy_project import settings
from courses.forms import CommentForm
from .models import Course, Notification, Section, Lesson, Comment, StudentCourses
from django.contrib.auth.models import User 
from django.contrib.auth.decorators import login_required 
from django.views.generic import CreateView


@login_required
def notification_view(request):
    notifications = Notification.objects.select_related('lesson', 'comment', 'from_user').filter(to_user=request.user.username) 
    for noti in notifications:
        noti.is_seen = True
        noti.save() 

    return render(request, 'notification.html')

def courses_list(request):
    query = request.GET.get('query', '')
    where = {}
    if query: 
        where['name__icontains'] = query
        courses = Course.objects.filter(**where) 
    else: 
        courses = Course.objects.all() 
    return render(request, 'index.html',{
        'courses':courses
    })

def course_detial(request, cid): 
    course = Course.objects.get(pk=cid) 


    return render(request, 'course_detail.html',{
        'course':course, 
        'public_key': settings.STRIPE_PUBLIC_KEY
    })


@login_required 
def my_courses(request): 
    courses = StudentCourses.objects.select_related('user', 'course').filter(user=request.user) 
    return render(request, 'courses/my_courses.html', {
        'courses':courses
    })

@login_required
def sections(request, cid):
    course = Course.objects.get(pk=cid) 
    student = StudentCourses.objects.filter(user_id = request.user.id, course_id = course.id)
    if not student: 
        return redirect('Courses_list')
    sections = Section.objects.select_related('course').filter(course=cid) 
    return render(request, 'courses/sections.html', {
        'sections':sections,
        'course_name':course.name,
        'course_name_en':course.name_en
    })


@login_required
def lesson_list(request, sid): 
    course = Course.objects.get(section=sid) 
    student = StudentCourses.objects.filter(user_id = request.user.id, course_id = course.id)
    if not student: 
        return redirect('Courses_list')
    lessons = Lesson.objects.select_related('section').filter(section=sid)
    return render(request, 'courses/lessons_list.html',{
        'lessons':lessons,
        'course_id': course.id,
        'course_name': course.name,
        'course_name_en': course.name_en,
    })

def find_username(body):
    search = re.search('(@)([A-z0-9]+\S[^\W])', body)
    if search:
        return search.group(2)
    else: 
        return False
    


@login_required
def lesson(request, lid): 
    course = Course.objects.get(lesson=lid) 
    student = StudentCourses.objects.filter(user_id = request.user.id, course_id = course.id)
    if not student: 
        return redirect('Courses_list')
    lesson = Lesson.objects.get(pk=lid)
    if request.method =='POST':
        form =CommentForm(request.POST)
        new_comment = form.save(commit=False)
        body = request.POST.get('body')
        username = find_username(body)
        if User.objects.filter(username=username).exists(): 
            new_comment.to_user= username 
        else: 
            new_comment.to_user= 'admin' 
        new_comment.body = body
        new_comment.user = request.user 
        new_comment.lesson = Lesson.objects.get(id=lid)
        new_comment.save() 
        return HttpResponseRedirect(request.path_info)
    else:
        form = CommentForm()
    return render(request, 'courses/lesson.html', {
        'lesson':lesson, 
        'form':form  
    })


    

# class CommentCreateView(CreateView): 
#     model = Comment 
#     form_class = CommentForm
#     http_method_names = ['post']

#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         lesson = Lesson.objects.get(pk= self.request.POST.get('lid'))
#         form.instance.lesson = lesson 
#         return super().form_valid(form)
    
#     def get_success_url(self) -> str:
#         return reverse('Lesson', args=[self.object.lesson.id])

courses/templates/courses/courses_list.html
<ul>
    {% for course in courses %}
    <li>{{course.name}}</li>
    {% endfor %}
</ul>

courses/templates/courses/lesson.html
{% extends 'base.html' %}
{% load i18n %}
{% load my_filter %}
{% block content %}

{% get_current_language as LANGUAGE_CODE %}
{% if LANGUAGE_CODE == 'ar' %}
    <div class="card mb-3">
        <div class="card-head">
            <h2 class="m-3 ">
                <a href="{% url 'MyCourses' %}">{{lesson.course.name}}</a>>
                <a href="{% url 'Course_section' lesson.course.id %}">{{lesson.section.name}}</a>>
                {{lesson.name}}
            </h2>
        </div>
        <video class="card-img-top" width="600" height="600" controls>
        <source src="{{ lesson.video.url }}" type="video/mp4">
    </video> 
        <div class="card-body">
            <h5 class="card-title">{{ lesson.name }}</h5>
            <p class="card-text">{{lesson.description}}</p>
        </div>
    </div>
{% else %}
    <div class="card mb-3">
        <div class="card-head">
            <h2 class="m-3 ">
                <a href="{% url 'MyCourses' %}">{{lesson.course.name_en}}</a>>
                <a href="{% url 'Course_section' lesson.course.id %}">{{lesson.section.name_en}}</a>>
                {{lesson.name_en}}
            </h2>
        </div>
        <video class="card-img-top" width="600" height="600" controls>
        <source src="{{ lesson.video.url }}" type="video/mp4">
    </video> 
        <div class="card-body">
            <h5 class="card-title">{{ lesson.name }}</h5>
            <p class="card-text">{{lesson.description}}</p>
        </div>
    </div>
{% endif %}

<div class="container mb-5 mt-5">
    <div class="card-header">
    {% trans "Comments" %} {{lesson.comment_set.all.count}}
    </div>
    {% for comment in lesson.comment_set.all %}
    <div class="card">
        <div class="card-header">
        {{comment.user.username}}
        </div>
        <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p>{{ comment.body|safe }}</p>
            <footer class="blockquote-footer">{% trans "Date" %}: {{comment.created_at|date:'D-m-Y'}}</footer>
        </blockquote>
        </div>
    </div>
    {% empty %}
    <div class="card">
        <div class="card-header">
        <h3>No comment yet</h3>
        </div>
    </div>
    {% endfor %}    
</div>

<!-- comment form  -->
<div class="container mb-5 mt-5">

<div class="card">
    <form method="post" >
        <input name="lid" type="hidden" value="{{ lesson.id }}">
        <div class="form-group">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit"class="btn btn-primary btn-lg btn-block" value="{% trans "Comment" %}">
        </div>
    </form>
</div>
    </div>
{% endblock content %}

courses/templates/courses/lesson_comment.html
{% load i18n %}




<div class="card">
<form method="post" action="">
    <div class="form-group">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit"class="btn btn-primary btn-lg btn-block" value="{% trans "Comment" %}">
    </div>
</form>

</div>

courses/templates/courses/lessons_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load my_filter %}
{% block content %}

{% get_current_language as LANGUAGE_CODE %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-5">
            {% if LANGUAGE_CODE == 'ar' %}
            <div class="card-head">
                <h2 class="m-3 ">
                    <a href="{% url 'MyCourses' %}">{% trans "My Courses" %}</a>>
                    <a href="{% url 'Course_section' course_id %}">{{ course_name }}</a>>
                </h2>
                </div>
                <ul class="list-group">
                    {% for lesson in lessons %}
                    <a href="{% url 'Lesson' lesson.id %}">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{lesson.name}}
                        </li>
                    </a>
                        {% endfor %}
                </ul>
            {% else %}
            <div class="card-head">
                <h2 class="m-3 ">
                    <a href="{% url 'MyCourses' %}">{% trans "My Courses" %}</a>>
                    <a href="{% url 'Course_section' course_id %}">{{ course_name_en }}</a>>
                </h2>
                </div>
                <ul class="list-group">
                    {% for lesson in lessons %}
                    <a href="{% url 'Lesson' lesson.id %}">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{lesson.name_en}}
                        </li>
                    </a>
                        {% endfor %}
                </ul>
              
            {% endif %}
        </div>
      </div>
 
  </div>

{% endblock content %}

courses/templates/courses/my_courses.html
{% extends 'base.html' %}
{% load i18n %}
{% load my_filter %}
{% block content %}

{% get_current_language as LANGUAGE_CODE %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            {% if LANGUAGE_CODE == 'ar' %}
            <ul class="list-group">
                    {% for paid in courses %}
                    <a href="{% url 'Course_section' paid.course.id%}">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{paid.course.name}}
                            <span class="badge badge-primary badge-pill text-secondary">{{paid.course.section_set.count}}</span>
                        </li>
                    </a>
                        {% endfor %}
                </ul>
            {% else %}
                <ul class="list-group">
                    {% for paid in courses %}
                    <a href="{% url 'Course_section' paid.course.id%}">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{paid.course.name_en}}
                            <span class="badge badge-primary badge-pill text-secondary">{{paid.course.section_set.count}}</span>
                        </li>
                    </a>
                        {% endfor %}
                </ul>

            {% endif %}

        </div>
    </div>
</div>

{% endblock content %}

courses/templates/courses/sections.html
{% extends 'base.html' %}
{% load i18n %}
{% load my_filter %}
{% block content %}

{% get_current_language as LANGUAGE_CODE %}
<div class="container-fluid">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
          {% if LANGUAGE_CODE == 'ar' %}
          <div class="card-head">
            <h2 class="m-3 ">
                <a href="{% url 'MyCourses' %}">{% trans "My Courses" %}</a>>
                {{ course_name }}
            </h2>
            </div>
          <ul class="list-group">
              {% for section in sections %}
              <a href="{% url 'Course_section_lessons' section.id %}">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  {{section.name}}
                  <span class="badge badge-primary badge-pill text-secondary">{{section.lesson_set.count}} {% trans "lessons" %}</span>
              </li>
              </a>
              {% endfor %}
          </ul>
          {% else %}
          <div class="card-head">
            <h2 class="m-3 ">
                <a href="{% url 'MyCourses' %}">{% trans "My Courses" %}</a>>
                {{ course_name_en }}
            </h2>
            </div>
          <ul class="list-group">
              {% for section in sections %}
              <a href="{% url 'Course_section_lessons' section.id %}">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  {{section.name_en}}
                  <span class="badge badge-primary badge-pill text-secondary">{{section.lesson_set.count}} {% trans "lessons" %}</span>
              </li>
              </a>
              {% endfor %}
          </ul>
            
          {% endif %}
        </div>
      </div>
 
  </div>

{% endblock content %}